spring:
  application:
    name: product-service

  config:
    import:
      - classpath:properties/datasource.yml
      - classpath:properties/jpa.yml
      - classpath:properties/eureka.yml

server:
  port: 19093